# numpy library

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
l=range(100)
%timeit [i**2 for i in l]

14.7 µs ± 1.27 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Creating Array

In [6]:
a=np.array([1,2,3,4,5]) #one dimension

In [7]:
a.ndim #says which dimension is it

1

In [9]:
b=np.array([[1,3,2],[4,5,6]])
b

array([[1, 3, 2],
       [4, 5, 6]])

In [10]:
b.ndim

2

In [11]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
c.ndim

3

In [13]:
a.shape #dispalys no.of columns

(5,)

In [14]:
b.shape #dispalys no.of rows and columns

(2, 3)

In [15]:
c.shape 

(1, 3, 3)

# Functions for Creating Array

In [16]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [17]:
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
a=np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [22]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
np.diag(a)

array([1, 2, 3, 4])

# Basic datatypes

In [24]:
a=np.array([1+2j,2+4j])
a.dtype

dtype('complex128')

In [25]:
a=np.array([True, False])
a.dtype

dtype('bool')

In [26]:
a=np.array(["Rams", "sri"])
a.dtype                            #unicode string code

dtype('<U4')

In [27]:
a=np.array(["RAMYASRI", "False"])   #Maximum length of the given string
a.dtype

dtype('<U8')

# indexing and slicing

In [28]:
a=np.arange(10)            #range from 0
a[5]                  #index start from 0

5

In [29]:
a= np.diag([1,2,3])
a[2,2]

3

In [30]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

# slicing

In [31]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a[1:8:2]

array([1, 3, 5, 7])

In [33]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [34]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [35]:
np.shares_memory(a,b)

True

In [36]:
b[0]=10
print(a)          #viewing
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [37]:
a=np.arange(10)
b=a[::2].copy()           #copying
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [38]:
np.shares_memory(a,b)

False

In [39]:
b[0]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# random generator

In [40]:
a=np.random.randint(0,20,15)
a

array([ 4,  0, 16,  9,  3,  8, 15, 15,  9,  8, 10,  2,  8,  3,  4])

# basic operations

In [42]:
import numpy as np

In [43]:
a=np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [44]:
a*0

array([0, 0, 0, 0])

In [45]:
a-1

array([0, 1, 2, 3])

In [46]:
a**2

array([ 1,  4,  9, 16])

In [47]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [48]:
b=np.ones(4)+1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [49]:
print(a*b)

[2. 4. 6. 8.]


In [50]:
print(a+b)

[3. 4. 5. 6.]


In [51]:
c=np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [52]:
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [53]:
print(c*c)
print("*************")
print(c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*************
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [54]:
a=np.array([1,2,3,4])
b=np.array([3,2,3,6])
print(a==b)

[False  True  True False]


In [55]:
a=np.array([1,2,3,4])
b=np.array([3,2,3,6])
print(a>b)

[False False False False]


In [56]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([3,4,5,6])
print(np.array_equal(a,b))

False


In [57]:
print(np.array_equal(a,c))

False


In [58]:
a=np.array([1,0,1,0],dtype="bool")#operational
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_or(a,b))

[ True  True  True False]


In [59]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")
print(np.logical_and(a,b))

[ True False False False]


In [60]:
a=np.arange(5)# trignometric
print(a)

[0 1 2 3 4]


In [61]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [63]:
print(np.exp(a))

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [64]:
#basic reductions
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [65]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [66]:
a.sum(axis=0)

array([4, 6])