# Covariance & Correlation

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv(r"C:\Users\Ramya\OneDrive\Documents\study_marks.csv")
df

Study_Hours  Marks
0          2.9   27.0
1          5.8   61.0
2          4.7   45.0
3          4.0   38.0
4          1.8   19.0
5          1.8    8.0
6          1.3    4.0
7          5.3   50.0
8          4.0   35.0
9          4.5   47.0

In [6]:
df.cov()

Study_Hours       Marks
Study_Hours     2.481000   28.906667
Marks          28.906667  348.711111

In [7]:
df.corr()

Study_Hours    Marks
Study_Hours      1.00000  0.98277
Marks            0.98277  1.00000

In [8]:
df=pd.read_csv(r"C:\Users\Ramya\OneDrive\Documents\temp_icecream_sales.csv")
df

Temperature  IceCream_Sales
0           20             200
1           22             220
2           24             250
3           26             270
4           28             300
5           30             320
6           32             350
7           34             370
8           36             400
9           38             420

In [9]:
df.cov()

Temperature  IceCream_Sales
Temperature       36.666667      455.555556
IceCream_Sales   455.555556     5666.666667

In [10]:
df.corr()

Temperature  IceCream_Sales
Temperature        1.000000        0.999406
IceCream_Sales     0.999406        1.000000

In [11]:
df=pd.read_csv(r"C:\Users\Ramya\OneDrive\Documents\TEMP.csv")
df

Temperature      Sunny
0           34         50
1           24         45
2           34         36
3           12         56
4           67         78
5           78         89
6           89         78

In [12]:
df.cov()

Temperature       Sunny
Temperature   867.571429  487.761905
    Sunny     487.761905  397.571429

In [13]:
data={
    "temp":[-20,-30,-40,-60],
    "hum":[100,150,140,130]
}
df=pd.DataFrame(data)
df

temp  hum
0   -20  100
1   -30  150
2   -40  140
3   -60  130

In [14]:
df.cov()

temp         hum
temp  291.666667 -133.333333
hum  -133.333333  466.666667

# normalization


In [15]:
s=pd.Series([1000,2000,3000,4000])
s

0    1000
1    2000
2    3000
3    4000
dtype: int64

In [16]:
v=((1000-1000)/(4000-1000))
v

0.0

In [17]:
v=((2000-1000)/(4000-1000))            #v=(x-min()/max()-min())
v

0.3333333333333333

In [18]:
v=((3000-1000)/(4000-1000))
v

0.6666666666666666

In [19]:
v=((4000-1000)/(4000-1000))
v

1.0

In [20]:
s.min()

1000

In [21]:
s.max()

4000

In [22]:
sd=(s-s.min())/(s.max()-s.min())
sd

0    0.000000
1    0.333333
2    0.666667
3    1.000000
dtype: float64

In [23]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [24]:
import pandas as pd

In [25]:
sd=MinMaxScaler().fit_transform(s.values.reshape(-1,1))
sd

array([[0.        ],
       [0.33333333],
       [0.66666667],
       [1.        ]])

In [26]:
data={
    "temp":[-20,-30,-40,-60],
    "hum":[100,150,140,130]
}
df=pd.DataFrame(data)
df

temp  hum
0   -20  100
1   -30  150
2   -40  140
3   -60  130

In [27]:
norm_data=MinMaxScaler().fit_transform(df)    ####normalization
norm_data
                            


array([[1.  , 0.  ],
       [0.75, 1.  ],
       [0.5 , 0.8 ],
       [0.  , 0.6 ]])

In [28]:
norm_df=pd.DataFrame(norm_data,columns=df.columns)
norm_df

temp  hum
0  1.00  0.0
1  0.75  1.0
2  0.50  0.8
3  0.00  0.6

# Standardization

In [29]:
s=pd.Series([1000,2000,3000,4000])
s

0    1000
1    2000
2    3000
3    4000
dtype: int64

In [30]:
s.mean()

2500.0

In [31]:
s.std()

1290.9944487358057

In [32]:
zscore=(s-s.mean())/s.std()
zscore

0   -1.161895
1   -0.387298
2    0.387298
3    1.161895
dtype: float64

In [33]:
zscore=StandardScaler().fit_transform(s.values.reshape(-1,1))
zscore

array([[-1.34164079],
       [-0.4472136 ],
       [ 0.4472136 ],
       [ 1.34164079]])

In [34]:
zscore=(s-s.mean())/s.std(ddof=0)
zscore

0   -1.341641
1   -0.447214
2    0.447214
3    1.341641
dtype: float64

In [35]:
data={
    "temp":[-20,-30,-40,-60],
    "hum":[100,150,140,130]
}
df=pd.DataFrame(data)
df

temp  hum
0   -20  100
1   -30  150
2   -40  140
3   -60  130

In [36]:
zscore=StandardScaler().fit_transform(df)
zscoredf=pd.DataFrame(zscore, columns=df.columns)

In [37]:
zscore

array([[ 1.18321596, -1.60356745],
       [ 0.50709255,  1.06904497],
       [-0.16903085,  0.53452248],
       [-1.52127766,  0.        ]])

In [39]:
zscoredf

temp       hum
0  1.183216 -1.603567
1  0.507093  1.069045
2 -0.169031  0.534522
3 -1.521278  0.000000